GET http://localhost:3000/app

###
Post http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedtoChannel": "Web Dev Simplified"
}
###
POST  http://localhost:3000
Content-Type: application/json

{
    "sport": "basketball",
    "datetime": "hello",
    "location": "stadium",
    "description": "hello"
}

###
DELETE http://localhost:3000/gameRoutes/66f8a26b3892a807abf093e2

